n = int(input("Enter: "))
while n <= 0: n = int(input("Enter: "))
string = ''
while n != 0:
    if n - 1000 >= 0:
        string+="M"
        n -= 1000
    elif n - 900 >= 0:
        string+="CM"
        n -= 900
    elif n - 500 >= 0:
        string+="D"
        n -= 500
    elif n - 400 >= 0:
        string+="CD"
        n -= 400
    elif n - 100 >= 0:
        string+="C"
        n -= 100
    elif n - 90 >= 0:
        string+="XC"
        n -= 90
    elif n - 50 >= 0:
        string+="L"
        n -= 50
    elif n - 40 >= 0:
        string+="XL"
        n -= 40
    elif n - 10 >= 0:
        string+="X"
        n-=10
    elif n - 9 >= 0:
        string+="IX"
        n-=9
    elif n - 5 >= 0:
        string+="V"
        n-=5
    elif n - 4 >= 0:
        string+="IV"
        n-=4
    elif n - 1 >= 0:
        string+="I"
        n-=1
print(string)
